<?php
$width=80;
$height=30;
$img=imagecreatetruecolor($width,$height);
$white=imagecolorallocate($img,255,255,255);
$randColor=imagecolorallocate($img,mt_rand(0,255),mt_rand(0,255),mt_rand(0,255));
$size=mt_rand(16,22);
$angle=mt_rand(-10,10);
$x=20;
$y=15;
$fontFile='./fonts/simkai.ttf';
$text=mt_rand(1000,9999);

session_start();
$_SESSION['checkcode']=$text;
imagettftext($img,$size,$angle,$x,$y,$randColor,$fontFile,$text);
header("content-type:image/png");
imagepng($img);
imagedestroy($img);
